export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="modded-fishy"

plugins=(git you-should-use zsh-autosuggestions zsh-fzf-history-search)

source $ZSH/oh-my-zsh.sh

alias rrm=trash
alias zconf="nvim ~/.zshrc && source ~/.zshrc"
alias lg="lazygit"
alias ls="exa -l -g --icons --git"
alias lt="exa -1 -a --icons --tree --git-ignore"
alias llt="exa -1 --icons --tree --git-ignore"
alias tz="TZ_LIST=\"Europe/Lisbon;Europe/London;US/Eastern,US-East;US/Pacific,US-Pacific;UTC\" tz"

# Editors
# alias kick="NVIM_APPNAME=kickstart nvim"
# alias lazy="NVIM_APPNAME=lazy nvim"
export EDITOR="nvim"

alias search="fzf --preview 'bat --color=always --style=numbers --line-range=:500 {}' | xargs nvim"
alias tldrf='tldr --list | fzf --preview "tldr {1} --color=always" --preview-window=right,70% | xargs tldr'
alias work="cd ~/dev"
alias webget="wget --mirror --convert-links --adjust-extension --page-requisites --no-parent"
alias nn="nvim ~/Documents/notes/"

# alias git-https="git remote set-url origin https://github.com/$(git remote get-url origin | sed 's/https:\/\/github.com\///' | sed 's/git@github.com://')"
# alias git-ssh="git remote set-url origin git@github.com:$(git remote get-url origin | sed 's/https:\/\/github.com\///' | sed 's/git@github.com://')"

##########
# HISTORY
##########

HISTFILE=$HOME/.zsh_history
HISTSIZE=50000
SAVEHIST=50000

# Immediately append to history file:
setopt INC_APPEND_HISTORY

# Record timestamp in history:
setopt EXTENDED_HISTORY

# Expire duplicate entries first when trimming history:
setopt HIST_EXPIRE_DUPS_FIRST

# Dont record an entry that was just recorded again:
setopt HIST_IGNORE_DUPS

# Delete old recorded entry if new entry is a duplicate:
setopt HIST_IGNORE_ALL_DUPS

# Do not display a line previously found:
setopt HIST_FIND_NO_DUPS

# Dont record an entry starting with a space:
setopt HIST_IGNORE_SPACE

# Dont write duplicate entries in the history file:
setopt HIST_SAVE_NO_DUPS

# Share history between all sessions:
setopt SHARE_HISTORY

# Execute commands using history (e.g.: using !$) immediatel:
unsetopt HIST_VERIFY

PATH="/Applications/CMake.app/Contents/bin":"$PATH"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

eval "$(direnv hook zsh)"

PATH="/opt/homebrew/opt/gnu-tar/libexec/gnubin:$PATH"

export LESS=' --HILITE-UNREAD --ignore-case --incsearch --jump-target=4 --LONG-PROMPT --no-init --quit-if-one-screen --RAW-CONTROL-CHARS --use-color --window=-4'
# removed options:
#     --chop-long-lines

eval "$(zoxide init --cmd cd zsh)"

# opam configuration
[[ ! -r /Users/palozano/.opam/opam-init/init.zsh ]] || source /Users/palozano/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null

# >>> juliaup initialize >>>

# !! Contents within this block are managed by juliaup !!

path=('/Users/palozano/.juliaup/bin' $path)
export PATH

# <<< juliaup initialize <<<

eval "$(starship init zsh)"
