export ZSH="$HOME/.oh-my-zsh"

# ZSH_THEME="modded-fishy"
ZSH_THEME="sammy" # set by `omz`

plugins=(git keychain gpg-agent you-should-use zsh-autosuggestions zsh-fzf-history-search fzf-tab asdf)

source $ZSH/oh-my-zsh.sh

alias rrm=trash
alias zconf="nvim ~/.zshrc && source ~/.zshrc"
alias dots="nvim ~/dev/dotfiles"
alias lg="lazygit"
alias ls="lsd -l -g --icon auto --git"
alias lt="lsd -1 -a --icon auto --tree --git"
alias llt="lsd -1 --icon auto --tree --git"
alias tz="TZ_LIST=\"Europe/Lisbon;Europe/London;US/Eastern,US-East;US/Pacific,US-Pacific;UTC\" tz"
# kitty
alias icat="kitten icat"

# Editors
alias astro="NVIM_APPNAME=astro nvim"
alias lazy="NVIM_APPNAME=lazy nvim"
alias chad="NVIM_APPNAME=nvchad nvim"
alias nu="nvim -u NONE"
alias old="NVIM_APPNAME=oldnvim nvim"
alias nn="nvim"
alias nt="nvim ~/Documents/notes/obsidian"
alias doom="emacs -nw"

export EDITOR="nvim"

# alias tmux="TERM=tmux-256color tmux"
# alias search="fzf --preview 'bat --color=always --style=numbers --line-range=:500 {}' | xargs nvim"
alias ss="fzf --preview 'bat --color=always --style=numbers --line-range=:500 {}'"
alias ns="fzf --preview 'bat --color=always --style=numbers --line-range=:500 {}' | xargs nvim"
alias tldrf='tldr --list | fzf --preview "tldr {1} --color=always" --preview-window=right,70% | xargs tldr'
alias work="cd ~/dev"
alias webget="wget --mirror --convert-links --adjust-extension --page-requisites --no-parent"
# alias nn="nvim ~/Documents/notes/"
alias r="ranger"

# alias git-https="git remote set-url origin https://github.com/$(git remote get-url origin | sed 's/https:\/\/github.com\///' | sed 's/git@github.com://')"
# alias git-ssh="git remote set-url origin git@github.com:$(git remote get-url origin | sed 's/https:\/\/github.com\///' | sed 's/git@github.com://')"
alias geu="git edit-unmerged"

###########
# FUNCTIONS
###########

tt () {
   mkdir -p -- "$1" && touch -- "$1"/"$2"
}

##########
# HISTORY
##########

HISTFILE=$HOME/.zsh_history
HISTSIZE=50000
SAVEHIST=50000

# Immediately append to history file:
setopt INC_APPEND_HISTORY

# Record timestamp in history:
setopt EXTENDED_HISTORY

# Expire duplicate entries first when trimming history:
setopt HIST_EXPIRE_DUPS_FIRST

# Dont record an entry that was just recorded again:
setopt HIST_IGNORE_DUPS

# Delete old recorded entry if new entry is a duplicate:
setopt HIST_IGNORE_ALL_DUPS

# Do not display a line previously found:
setopt HIST_FIND_NO_DUPS

# Dont record an entry starting with a space:
setopt HIST_IGNORE_SPACE

# Dont write duplicate entries in the history file:
setopt HIST_SAVE_NO_DUPS

# Share history between all sessions:
setopt SHARE_HISTORY

# Execute commands using history (e.g.: using !$) immediatel:
unsetopt HIST_VERIFY

PATH="/Applications/CMake.app/Contents/bin":"$PATH"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

eval "$(direnv hook zsh)"

PATH="/opt/homebrew/opt/gnu-tar/libexec/gnubin:$PATH"
PATH="/Library/TeX/texbin:$PATH"

export LESS=' --HILITE-UNREAD --ignore-case --incsearch --jump-target=4 --LONG-PROMPT --no-init --quit-if-one-screen --RAW-CONTROL-CHARS --use-color --window=-4'
# removed options:
#     --chop-long-lines

export GPG_TTY="$(tty)"

# pnpm
export PNPM_HOME="/Users/palozano/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# elixir's repl iex has this
export ERL_AFLAGS="-kernel shell_history enabled"

source <(fzf --zsh)
eval "$(zoxide init --cmd cd zsh)"
# eval "$(starship init zsh)"

