export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="modded-fishy"

plugins=(git you-should-use zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

alias rrm=trash
alias zconf="nvim ~/.zshrc && source ~/.zshrc"
alias lg="lazygit"
alias ls="exa -l -g --icons --git"
alias lt="exa -1 -a --icons --tree --git-ignore"
alias llt="exa -1 --icons --tree --git-ignore"
alias tz="TZ_LIST=\"Europe/Lisbon;Europe/London;US/Eastern,US-East;US/Pacific,US-Pacific;UTC\" tz"

# Editors
# alias kick="NVIM_APPNAME=kickstart nvim"
# alias lazy="NVIM_APPNAME=lazy nvim"
export EDITOR="nvim"

alias search="fzf --preview 'bat --color=always --style=numbers --line-range=:500 {}' | xargs nvim"
alias tldrf='tldr --list | fzf --preview "tldr {1} --color=always" --preview-window=right,70% | xargs tldr'
alias work="cd ~/dev/repyh"
alias webget="wget --mirror --convert-links --adjust-extension --page-requisites --no-parent"

PATH="/Applications/CMake.app/Contents/bin":"$PATH"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

eval "$(direnv hook zsh)"

PATH="/opt/homebrew/opt/gnu-tar/libexec/gnubin:$PATH"

export LESS=' --HILITE-UNREAD --ignore-case --incsearch --jump-target=4 --LONG-PROMPT --no-init --quit-if-one-screen --RAW-CONTROL-CHARS --use-color --window=-4'
# removed options:
#     --chop-long-lines
