return {
  'saecki/crates.nvim',
  tag = 'stable',
  dependencies = { 'nvim-lua/plenary.nvim' },
  config = function()
    vim.keymap.set('n', '<leader>ct', require('crates').toggle, { silent = true, desc = 'Toggle crates' })
    vim.keymap.set('n', '<leader>cr', require('crates').reload, { silent = true, desc = 'Reload crates' })

    vim.keymap.set('n', '<leader>cv', require('crates').show_versions_popup,
      { silent = true, desc = 'Show versions popup' })
    vim.keymap.set('n', '<leader>cf', require('crates').show_features_popup,
      { silent = true, desc = 'Show features popup' })
    vim.keymap.set('n', '<leader>cd', require('crates').show_dependencies_popup,
      { silent = true, desc = 'Show dependencies popup' })

    vim.keymap.set('n', '<leader>cu', require('crates').update_crate, { silent = true, desc = 'Update crate' })
    vim.keymap.set('v', '<leader>cu', require('crates').update_crates, { silent = true, desc = 'Update crates' })
    -- vim.keymap.set('n', '<leader>ca', require('crates').update_all_crates, { silent = true, desc = 'Update all crates' }),
    vim.keymap.set('n', '<leader>cU', require('crates').upgrade_crate, { silent = true, desc = 'Upgrade crate' })
    vim.keymap.set('v', '<leader>cU', require('crates').upgrade_crates, { silent = true, desc = 'Upgrade crates' })
    vim.keymap.set('n', '<leader>cA', require('crates').upgrade_all_crates,
      { silent = true, desc = 'Upgrade all crates' })
    vim.keymap.set('n', '<leader>ce', require('crates').expand_plain_crate_to_inline_table,
      { silent = true, desc = 'Expand plain crate to inline table' })
    vim.keymap.set('n', '<leader>cE', require('crates').extract_crate_into_table,
      { silent = true, desc = 'Extract crate into table' })

    vim.keymap.set('n', '<leader>cH', require('crates').open_homepage, { silent = true, desc = 'Open homepage' })
    vim.keymap.set('n', '<leader>cR', require('crates').open_repository, { silent = true, desc = 'Open repository' })
    vim.keymap.set('n', '<leader>cD', require('crates').open_documentation,
      { silent = true, desc = 'Open documentation' })
    vim.keymap.set('n', '<leader>cC', require('crates').open_crates_io, { silent = true, desc = 'Open crates.io' })
    require('crates').setup {
      smart_insert = true,
      insert_closing_quote = true,
      avoid_prerelease = true,
      autoload = true,
      autoupdate = true,
      autoupdate_throttle = 250,
      loading_indicator = true,
      date_format = "%Y-%m-%d",
      thousands_separator = ".",
      notification_title = "Crates",
      curl_args = { "-sL", "--retry", "1" },
      max_parallel_requests = 80,
      -- expand_crate_moves_cursor = true,
      open_programs = { "xdg-open", "open" },
      disable_invalid_feature_diagnostic = false,
      -- enable_update_available_warning = true,
      text = {
        loading = "   Loading",
        version = "   %s",
        prerelease = "   %s",
        yanked = "   %s",
        nomatch = "   No match",
        upgrade = "   %s",
        error = "   Error fetching crate",
      },
      highlight = {
        loading = "CratesNvimLoading",
        version = "CratesNvimVersion",
        prerelease = "CratesNvimPreRelease",
        yanked = "CratesNvimYanked",
        nomatch = "CratesNvimNoMatch",
        upgrade = "CratesNvimUpgrade",
        error = "CratesNvimError",
      },
      popup = {
        autofocus = false,
        hide_on_select = false,
        copy_register = '"',
        style = "minimal",
        border = "none",
        show_version_date = false,
        show_dependency_version = true,
        max_height = 30,
        min_width = 20,
        padding = 1,
        text = {
          title = " %s",
          pill_left = "",
          pill_right = "",
          description = "%s",
          created_label = " created        ",
          created = "%s",
          updated_label = " updated        ",
          updated = "%s",
          downloads_label = " downloads      ",
          downloads = "%s",
          homepage_label = " homepage       ",
          homepage = "%s",
          repository_label = " repository     ",
          repository = "%s",
          documentation_label = " documentation  ",
          documentation = "%s",
          crates_io_label = " crates.io      ",
          crates_io = "%s",
          categories_label = " categories     ",
          keywords_label = " keywords       ",
          version = "  %s",
          prerelease = " %s",
          yanked = " %s",
          version_date = "  %s",
          feature = "  %s",
          enabled = " %s",
          transitive = " %s",
          normal_dependencies_title = " Dependencies",
          build_dependencies_title = " Build dependencies",
          dev_dependencies_title = " Dev dependencies",
          dependency = "  %s",
          optional = " %s",
          dependency_version = "  %s",
          loading = "  ",
        },
        highlight = {
          title = "CratesNvimPopupTitle",
          pill_text = "CratesNvimPopupPillText",
          pill_border = "CratesNvimPopupPillBorder",
          description = "CratesNvimPopupDescription",
          created_label = "CratesNvimPopupLabel",
          created = "CratesNvimPopupValue",
          updated_label = "CratesNvimPopupLabel",
          updated = "CratesNvimPopupValue",
          downloads_label = "CratesNvimPopupLabel",
          downloads = "CratesNvimPopupValue",
          homepage_label = "CratesNvimPopupLabel",
          homepage = "CratesNvimPopupUrl",
          repository_label = "CratesNvimPopupLabel",
          repository = "CratesNvimPopupUrl",
          documentation_label = "CratesNvimPopupLabel",
          documentation = "CratesNvimPopupUrl",
          crates_io_label = "CratesNvimPopupLabel",
          crates_io = "CratesNvimPopupUrl",
          categories_label = "CratesNvimPopupLabel",
          keywords_label = "CratesNvimPopupLabel",
          version = "CratesNvimPopupVersion",
          prerelease = "CratesNvimPopupPreRelease",
          yanked = "CratesNvimPopupYanked",
          version_date = "CratesNvimPopupVersionDate",
          feature = "CratesNvimPopupFeature",
          enabled = "CratesNvimPopupEnabled",
          transitive = "CratesNvimPopupTransitive",
          normal_dependencies_title = "CratesNvimPopupNormalDependenciesTitle",
          build_dependencies_title = "CratesNvimPopupBuildDependenciesTitle",
          dev_dependencies_title = "CratesNvimPopupDevDependenciesTitle",
          dependency = "CratesNvimPopupDependency",
          optional = "CratesNvimPopupOptional",
          dependency_version = "CratesNvimPopupDependencyVersion",
          loading = "CratesNvimPopupLoading",
        },
        keys = {
          hide = { "q", "<esc>" },
          open_url = { "<cr>" },
          select = { "<cr>" },
          select_alt = { "s" },
          toggle_feature = { "<cr>" },
          copy_value = { "yy" },
          goto_item = { "gd", "K", "<C-LeftMouse>" },
          jump_forward = { "<c-i>" },
          jump_back = { "<c-o>", "<C-RightMouse>" },
        },
      },
      src = {
        insert_closing_quote = true,
        text = {
          prerelease = "  pre-release ",
          yanked = "  yanked ",
        },
        -- cmp = {
        --   enabled = false,
        --   use_custom_kind = true,
        --   kind_text = {
        --     version = "Version",
        --     feature = "Feature",
        --   },
        --   kind_highlight = {
        --     version = "CmpItemKindVersion",
        --     feature = "CmpItemKindFeature",
        --   },
        -- },
        coq = {
          enabled = false,
          name = "Crates",
        },
      },
      null_ls = {
        enabled = false,
        name = "Crates",
      },
      on_attach = function(bufnr) end,
    }
  end,
}
